# Generated by Django 5.2 on 2025-05-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_picture',
            field=models.ImageField(blank=True, null=True, upload_to='ticket_picture/'),
        ),
    ]
